import localFont from "next/font/local";

import Navbar from "@/components/common/navbar";
import { cn } from "@/lib/utils";

import "./globals.css";

const customFont = localFont({
  src: [
    {
      path: "../public/fonts/StyreneALC-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/StyreneALC-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/StyreneALC-Black.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/StyreneALC-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
});

export const metadata = {
  title: "Artel Electronics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background", customFont.className)}>
        <Navbar />
        <div className="-mt-[136px]">{children}</div>
      </body>
    </html>
  );
}
